version: '3.9'

services:
  web:
    image: nginx:1.27.1
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    environment:
      - SERVER_NAME=localhost
    depends_on:
      - app
    networks:
      - laravel-network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=r00tP@ss3014
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge